version: "3"
services:

  db:
    image: mysql
    restart: always
    environment:
     - MYSQL_DATABASE=db
     - MYSQL_USER=user2
     - MYSQL_PASSWORD=passwd2
     - MYSQL_RANDOM_ROOT_PASSWORD=yes

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
          - db
